// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Address : BaseEntity
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string CustomerName { get; set; }

    public string PhoneNumber { get; set; }

    public int CountryId { get; set; }

    public string StreetNumber { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string Ward { get; set; }

    public string Postcode { get; set; }

    public string Province { get; set; }

    public bool IsDefault { get; set; }
    
    public virtual Country Country { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}