// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Blog : BaseEntity
{
    public Guid Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Thumbnail { get; set; }
    public Guid UserId { get; set; }
    public virtual ICollection<BlogSection> BlogSections { get; set; } = new List<BlogSection>();
    public virtual User User { get; set; }
    
}