// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Brand
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string ImageUrl { get; set; }

    //public bool? IsLiked { get; set; }
    public int CountryId { get; set; }
    public virtual Country Country { get; set; }
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}