// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class CancelReason
{
    public Guid Id { get; set; }
    public string Description { get; set; }
    public decimal RefundRate { get; set; }
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}