// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class CartItem
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public Guid ProductItemId { get; set; }
    public int Quantity { get; set; }
    public virtual ProductItem ProductItem { get; set; }
    public virtual User User { get; set; }
}