// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Country 
{
    public int Id { get; set; }

    public string CountryCode { get; set; }

    public string CountryName { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();
}