// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Order : BaseEntity
{
    public Guid Id { get; set; }
    public string Status { get; set; }
    public decimal OrderTotal { get; set; }
    public Guid? CancelReasonId { get; set; }
    public Guid UserId { get; set; }
    public Guid PaymentMethodId { get; set; }
    public Guid AddressId { get; set; }
    public Guid? VoucherId { get; set; }
    public virtual Address Address { get; set; }
    public virtual CancelReason CancelReason { get; set; }
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
    public virtual PaymentMethod PaymentMethod { get; set; }
    public virtual ICollection<StatusChange> StatusChanges { get; set; } = new List<StatusChange>();
    public virtual User User { get; set; }
    public virtual Voucher Voucher { get; set; }
}