// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Product : BaseEntity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string EnglishName { get; set; }

    public string Description { get; set; }

    public int SoldCount { get; set; }

    public double Rating { get; set; }

    public string StorageInstruction { get; set; }

    public string UsageInstruction { get; set; }

    public string DetailedIngredients { get; set; }

    public string MainFunction { get; set; }

    public string Texture { get; set; }

    public decimal Price { get; set; }

    public decimal MarketPrice { get; set; }

    public string KeyActiveIngredients { get; set; }

    public string ExpiryDate { get; set; }

    public string SkinIssues { get; set; }

    public Guid? ProductStatusId { get; set; }

    public Guid? BrandId { get; set; }

    public Guid ProductCategoryId { get; set; }
    public virtual Brand Brand { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ICollection<ProductForSkinType> ProductForSkinTypes { get; set; } = new List<ProductForSkinType>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductItem> ProductItems { get; set; } = new List<ProductItem>();

    public virtual ProductStatus ProductStatus { get; set; }
}