// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ProductImage
{
    public Guid Id { get; set; }

    public string ImageUrl { get; set; }

    public bool IsThumbnail { get; set; }

    public Guid ProductId { get; set; }
    public virtual Product Product { get; set; }
}