// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ProductCategory
{
    public Guid Id { get; set; }

    public Guid? ParentCategoryId { get; set; }

    public string CategoryName { get; set; }
    public virtual ICollection<ProductCategory> InverseParentCategory { get; set; } = new List<ProductCategory>();

    public virtual ProductCategory ParentCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Variation> Variations { get; set; } = new List<Variation>();
}