// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ProductItem
{
    public Guid Id { get; set; }

    public int QuantityInStock { get; set; }

    public string ImageUrl { get; set; }

    public decimal Price { get; set; }
    public decimal MarketPrice { get; set; }
    public decimal PurchasePrice { get; set; }
    public Guid ProductId { get; set; }
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductConfiguration> ProductConfigurations { get; set; } = new List<ProductConfiguration>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}