// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ProductConfiguration
{
    public Guid Id { get; set; }

    public Guid ProductItemId { get; set; }

    public Guid VariationOptionId { get; set; }
    public virtual ProductItem ProductItem { get; set; }

    public virtual VariationOption VariationOption { get; set; }
}