// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class QuizResult : BaseEntity
{
    public Guid Id { get; set; }

    public string Score { get; set; }

    public Guid SkinTypeId { get; set; }

    public Guid? QuizSetId { get; set; }
    public virtual QuizSet QuizSet { get; set; }

    public virtual SkinType SkinType { get; set; }
}