// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class QuizQuestion : BaseEntity
{
    public Guid Id { get; set; }

    public Guid SetId { get; set; }

    public string Value { get; set; }

    public Guid? QuizSetId { get; set; }
    public virtual ICollection<QuizOption> QuizOptions { get; set; } = new List<QuizOption>();

    public virtual QuizSet QuizSet { get; set; }
}