// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Review : BaseEntity
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public Guid ProductItemId { get; set; }

    public float RatingValue { get; set; }
    public string Comment { get; set; }
    public virtual ProductItem ProductItem { get; set; }
    public virtual Reply Reply { get; set; }
    public virtual ICollection<ReviewImage> ReviewImages { get; set; } = new List<ReviewImage>();
    public virtual User User { get; set; }
}