// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ReviewImage
{
    public Guid Id { get; set; }
    public Guid ReviewId { get; set; }
    public string ImageUrl { get; set; }
    public virtual Review Review { get; set; }
}