// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class SkinAnalysisRecommendation
{
    public Guid Id { get; set; }
    
    public Guid SkinAnalysisResultId { get; set; }
    
    public Guid ProductId { get; set; }
    
    public string RecommendationReason { get; set; }
    
    public int PriorityScore { get; set; }
    
    // Navigation properties
    public virtual SkinAnalysisResult SkinAnalysisResult { get; set; }
    
    public virtual Product Product { get; set; }
}