// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class SkinAnalysisIssue
{
    public Guid Id { get; set; }
    
    public Guid SkinAnalysisResultId { get; set; }
    
    public string IssueName { get; set; }
    
    public string Description { get; set; }
    
    public int Severity { get; set; }
    
    // Navigation property
    public virtual SkinAnalysisResult SkinAnalysisResult { get; set; }
}