// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class SkinAnalysisResult : BaseEntity
{
    public Guid Id { get; set; }

    public string ImageUrl { get; set; }
    
    public Guid UserId { get; set; }
    
    public Guid SkinTypeId { get; set; }
    
    // Skin condition scores
    public int AcneScore { get; set; }
    
    public int WrinkleScore { get; set; }
    
    public int DarkCircleScore { get; set; }
    
    public int DarkSpotScore { get; set; }
    
    public int HealthScore { get; set; }
    
    // Enhanced analysis data
    public int OilinessLevel { get; set; }
    
    public int DrynessLevel { get; set; }
    
    public int SensitivityLevel { get; set; }
    
    // Store full result as JSON
    public string FullAnalysisJson { get; set; }
    
    // Navigation properties
    public virtual User User { get; set; }
    
    public virtual SkinType SkinType { get; set; }
    
    public virtual ICollection<SkinAnalysisIssue> SkinAnalysisIssues { get; set; } = new List<SkinAnalysisIssue>();
    
    public virtual ICollection<SkinAnalysisRecommendation> SkinAnalysisRecommendations { get; set; } = new List<SkinAnalysisRecommendation>();
}