// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class StatusChange
{
    public Guid Id { get; set; }

    public DateTimeOffset Date { get; set; }
    public string Status { get; set; }

    public Guid OrderId { get; set; } 
    public virtual Order Order { get; set; }
}