// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Variation : BaseEntity
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public Guid? ProductCategoryId { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ICollection<VariationOption> VariationOptions { get; set; } = new List<VariationOption>();
}