// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class VariationOption : BaseEntity
{
    public Guid Id { get; set; }

    public string Value { get; set; }

    public Guid VariationId { get; set; }

    public virtual ICollection<ProductConfiguration> ProductConfigurations { get; set; } = new List<ProductConfiguration>();

    public virtual Variation Variation { get; set; }
}