// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Voucher : BaseEntity
{
    public Guid Id { get; set; }
    public string Code { get; set; }
    public string Description { get; set; }
    public string Status { get; set; }

    public double DiscountRate { get; set; }
    public int UsageLimit { get; set; }

    public double MinimumOrderValue { get; set; }

    public DateTimeOffset StartDate { get; set; }

    public DateTimeOffset EndDate { get; set; }
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}